import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layouts from "../components/Layouts";

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<Layouts>
			<Head>
				<title>SIM Examination</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Component {...pageProps} />
		</Layouts>
	);
}

export default MyApp;
